### ISSUE TITLE
Support OS X in our demo

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#180]
Currently we use `docker-compose`. On OS X socket files which `cardano-node` use does not work in it.

So currently we suggest to use VM to start project on OS X. If there will be demand for OS X support we could think of more convenient solution.

**UPD:**

Current plan is try to run REPL inside containers, as hydra does. If it works: provide `Makefile` shortcut and add to README.

**Comment by nazrhom** [comment]
This is partially solved by the PR above. There is now an image for the CLI as well that can be built through nix. This image is not included in the compose file, but can be run on its own by a mac os user to be able to speak to the cardano-node
