### ISSUE TITLE
Solve "collaterals on L2" problem

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#193]
There are two problems:

1. To make `makeTransactionBody` not fail on no-collateral Tx
2. To make ledger accept Tx without transactions

Possible solutions:

1. Use `TxInsCollateral []` instead of `TxInsCollateralNone`, like hydra team1 do. Seems to help with 1, but not 2.
2. Place invalid UTxO for collateral
3. Change ProtocolParams to ensure zero collateral and hope this would help with ledger.
4. Actually commit UTxOs into Hydra

**Comment by uhbif19** [comment]
Copy from slack:

> OK. Since we cannot avoid having to use collateral inputs in L2 transactions, I propose the following approach for the Hydra Auction:
> Start the Hydra Head with protocol parameters that make transaction fees always zero, and thus collateral fees always zero too.
> Commit two utxos to the Hydra Head from two different delegates:
> the standing bid utxo
> a utxo with 2.5 ADA (sufficient as collateral for anything on L2) locked under a VKey for which all delegates have the private key locked under a native script that ANY delegate can unilaterally spend
> Every NewBid transaction on L2 will spend the standing bid utxo as input and use the 2.5 ADA utxo as collateral.
> After the Hydra Head fans out the 2 utxos, the delegate who contributed the 2.5 ADA should retrieve it from the collateral utxo. Other delegates can steal the 2.5 ADA, but should not do so according to the "honor rule." Anyway, even if they do steal it, only 2.5 ADA is lost.
> What do you think?
> 

---

@GeorgeFlerovsky

I see obstacle with your idea on committing single UTxO by delegate not commuting staging bid. We need to select that single delegate. We could use `Head Id` for this, but that way we need to know all Head Ids, and know which one commited standing bid. I see following ways to handle this:

1. Listen to Hydra events to select UTxO-for-collateral commiting delegate
2. Commit UTxO-for-collaterals by all delegates except one
3. Commit ADA with standing bid and separate ADA from this later.

Option 2 requires more money so is less closer-to-reality.

1 seems to me as more complex, cuz requires more off-chain code and delegate logic. While it is probably uses lesser on-chain resources by not changing on-chain scripts.

---

The problem of having rights to spend from address is covered by having some pre-defined private key to use for UTxO-for-collateral address.

**Comment by nazrhom** [comment]
@ch1bo has a PR up to allow committing multiple UTxOs. That sounds like the best solution to me, as it does not require any extra code.
We do have an issue with getting the new Hydra version though, atm we are starting up the hydra nodes through docker-compose, in that we rely on the latest released version (currently 0.8.1). To benefit from hydra updates we would need a new version released atm

**Comment by ch1bo** [comment]
> We do have an issue with getting the new Hydra version though, atm we are starting up the hydra nodes through docker-compose, in that we rely on the latest released version (currently 0.8.1). To benefit from hydra updates we would need a new version

As you are using the docker distribution, you could use it as soon as it is on `master` using the `unstable` docker image tag. That being said, the [mentioned PR](https://github.com/input-output-hk/hydra/pull/774) is still in draft and has some big TODOs on it - don't expect this to happen before a couple weeks from now.

**Comment by uhbif19** [comment]
Saving current decision proccess.

As far as we currently understand, we cannot avoid collateral usage
for following reasons:

1. Ledger code does not cover case of zero collateral and thus
   require non-empty collateral list
2. Collaterals are probably required on-chain for the same reason as on L1
   (but that is to be discussed further)

There is a bunch main concerns regarding collateral:

1. It should be placed on L2 with `Commit` command.
2. The way to place it should not require
3. It should be usable by transaction.
   That means it should be locked by some key which is known
   to bidder and/or delegate.
4. This protocol should be as simple and not blocking as possible
   as measured by number and dependencies of required transactions
5. In production version bidders/delgates should not be able to lock
   or steal collateral utxos.
6. In production version collateral money should go back to owners after
   Hydra closing.


Locking collateral for delegates is not really important - they
always can lock or close L2. Stealing by delegates seems bad though.

Current decisions:

* For time being every delegate (except one commiting standing bid)
  do commit collateral ADA onto some pre-known-by-anyone key.
  For that they first commit collateral they do own and
  then transfer it onto pre-known-by-anyone
* Once Hydra will support multiple UTxO
   committing  (should be before our release) we move onto
  "all delegates do commit UTxO-for-collateral they do own".
  This solution seem to cover all requirements.
