### ISSUE TITLE
Add bidder authentication in NewBid transactions

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#203]
Current plan is to include bidder signature in Tx datum and check it on chain.

### Possible signing solutions

We probably would need both signatures. Bidder signature should be checked on chain, delegate signature is required to spend collateral (see #193). First signature only should be accessible by on-chain code, while second can only be regular Cardano Tx signature

There is multiple ways to do signing in presence of delegate server:

1. Frontend sign datum and send it to delegate server. Delegate server creates, signs (optionally) and submits Tx.
2. Create and sign whole Tx by Frontend. Delegate server only submits it to L2.
3. Create and sign whole Tx by Frontend. Delegate server parses Tx, signs it and submits to L2.

I think all of them are possible.

Signed datum actually can be checked on chain, because three is `verifySignature` Plutus primitive and datum could be serialized by hand (see: https://app.slack.com/client/T01UN827FQV/C028AD4LJGY).

Parsing by delegate server looks to be possible using of `SerialiseCBOR Tx` instance.

### Selected signing solution

Solution 1 costs a lot on chain, because we need to re-serialize part of datum and serializing integer  works bad on chain. See #220 
Solution 2 does not provide delegate signature.
Solution 3 is bad because requires signing by bidder. In our model we presume that in production this should be done with user wallet, so this would be slow, while Tx input on L2 may be invalidated quickly. Also this requires Tx serialization (which only works with CBOR).

**UPD:** Selected solution is 1, as long as transactions fit within blockchain constraints. We will deal with tx optimization later.
@GeorgeFlerovsky 

That means that last off-chain part of issue is blocked by #158 and #175

### Solution parts:

- [x] Select signing scheme
- [ ] Check that bidder signed bid and ensure delegate server/frontend do those signing

**Comment by nazrhom** [comment]
@uhbif19 I thought the decision here was to parametrise the auction terms by a list of accepted bidders (cfr. https://github.com/mlabs-haskell/hydra-auction/blob/staging/doc/adr/2023-01-09_003-open_vs_closed_auctions.md)

**Comment by nazrhom** [comment]
Current implementation plan (requires #158)

- add signers field to autoCreateTx
- create Tx.StandingBid.newBidL2 which does not use collateral and returns tx
- create newBidL2 in cli Actions which uses new function to generate tx, serialise it to CBOR and submits it to delegate server
- update delegate server to receive CBOR encoded tx in new bid
- delegate server de-serializes tx, adds collateral + extra sig
- delegate server submits tx to hydra node

**Comment by nazrhom** [comment]
I can get away with just serialising with files before we have the CLI -> Delegate server layer

**Comment by uhbif19** [comment]
@nazrhom What is the point of serializing with files?
