### ISSUE TITLE
Add delegate server into `docker-compose`

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#206]
Scope of task is just to add delegate nodes to docker compose. For now they do not have any config or links.

Probably need to build Docker image with our Nix env.

Blocked by #169

**Comment by nazrhom** [comment]
https://github.com/mlabs-haskell/hydra-auction/pull/187 Merging this would be quite helpful here. Since we are using ssh for our build, we need to correctly setup the docker image with ssh keys (which is a bit annoying)

**Comment by nazrhom** [comment]
Also, if we want to have delegate nodes in compose, then why not have also the CLI there? This will fix the issues with osx as well

**Comment by uhbif19** [comment]
Delegates are servers. And Delegate server should be started with Hydra nodes by same actor. So our `docker-compose` emulate Delegate server and Cardano node admins, while Frontend CLI is started as use wishes.

**Comment by nazrhom** [comment]
As discussed today in the meeting we agreed to build these images with nix.
This means we will have a nix build step (where nix builds the image for delegate servers), before being able to start docker-compose.
Our docker-compose will reference these images

**Comment by nazrhom** [comment]
Sorry, forgot to link the relevant PR here.

Closed by #219
