### ISSUE TITLE
Bidder auction approval off-chain communiction

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#222]
There is no understanding how to do this yet.

I see two possible tasks on that: sending approval from seller to bidder and requesting approval by bidder.

I think both those can just be just broadcasted to all clients by delegate server. Currently we do not check delegate clients - so not-yet-approved bidders can connect and wait for their approval.

How messages could be shared between delegates? I see two ways:

* Use existing Hydra connection. All transactions are broadcasted, so we can broadcast messages by adding it to transaction (using its datum?). We could commit separate UTxO for that purpose or just reuse collaterals.
* We can broadcast messages P2P. Delegates IPs could be known ahead, because we already require that for Hydra nodes.

Another issue I see is saving approvals for clients connected after being approved ahead of time. We could store that approvals on Delegate server or just re-send them by seller upon request.

Another questions for this issue:

* Do we need to implement that at all?
* Do we need approval request or only approval sending?
* What should be CLI interface for approving?

**Comment by GeorgeFlerovsky** [comment]
I don't think that this functionality belongs in the Delegate Server.

In the real world, there would be an auction app platform that would handle direct seller-bidder interactions like this, as well as keep track of the Hydra Heads and delegate servers available.

I suppose we could have delegate servers register/deregister with the auction app platform as L2 bid-hosting providers, and the auction app platform would query the Cardano node to confirm that the corresponding Hydra Heads exist.

Either the auction app platform or the frontend (or both) should cache the seller signatures authorizing bidders' participation in auctions.

```mermaid
flowchart TB
  subgraph Auction App
    seller([Seller])
    bidder([Bidder])
    frontend(Frontend CLI)
    auctionPlatformServer(Auction Platform Server)
  end

  subgraph Hydra-based Auction Hosting
    delegate([Delegate])
    delegateServer(Delegate server)
    hydraNode(Hydra node)
  end

  subgraph Cardano
    cardanoNode(Cardano node)
  end

  admin([Admin])

  admin -- start/stop -----> cardanoNode
  admin -- start/stop --> auctionPlatformServer
  auctionPlatformServer -- query --> cardanoNode
  seller -- request --> frontend
  bidder -- request --> frontend
  frontend -- request --> auctionPlatformServer
  frontend -- request --> cardanoNode
  frontend -- request --> delegateServer
  delegateServer -- request --> hydraNode
  delegateServer -- register/deregister --> auctionPlatformServer
  delegate -- start/stop ---> delegateServer
  delegate -- start/stop ---> hydraNode
  hydraNode -- request --> cardanoNode
```

**Comment by uhbif19** [comment]
Well that means yet another server. 

We could/should add available Hydra Heads tracking as well, is delegates gonna register anyway. Also there I see three options how to do register delegate server and/or Head:

1. Just believe everyone that they are Delegate servers
2. Ask for their Utxo with PT Hydra token and some signing with their Cardano key
3. Listen to L1 and found new Heads. Did not think how to filter one related  to auctions though. Also I do not know how reliable and easy to use are Cardano event streaming solutions.

Also, 

> I don't think that this functionality belongs in the Delegate Server.

You are talking about delegate-to-delegate communication part? Or you think all client-to-client communication should be performed with Auction Platform Server?

**Comment by uhbif19** [comment]
Subsumed by #270
