### ISSUE TITLE
Delegate support for fee distribution

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#304]
Follow up for #255 
Blocked by #255 

Todo:

- [ ] Add correct list of delegates to AuctionTerms (probably should be received from delegate server)
- [ ] Create tx to distribute fee by delegate server (how to select one to submit tx?)

**Comment by uhbif19** [comment]
Seems that we cannot obtain `delegates :: ![PubKeyHash]`, because Hydra only gives us Hydra keys, not L1.

It does not seem to be used anyway. We could just store `delegatesCount`.

@GeorgeFlerovsky ?

**Comment by GeorgeFlerovsky** [comment]
@uhbif19 
What do you mean "it's not used"?

How do you know that the fees went to the right people?

**Comment by uhbif19** [comment]
@GeorgeFlerovsky 

Lol, right, it is used.

Seems like Hydra do not give L1 pubkeys in API.

Actually Delegate knows L1 keys, cuz it needs to speak to it. But how will it get all other delegates keys?
We could use Platform server, of course, but this means long block until then.

**Comment by GeorgeFlerovsky** [comment]
> @GeorgeFlerovsky 
> 
> Lol, right, it is used.
> 
> Seems like Hydra do not give L1 pubkeys in API.
> 
> Actually Delegate knows L1 keys, cuz it needs to speak to it. But how will it get all other delegates keys?
> We could use Platform server, of course, but this means long block until then.

No, platform server might be the right place to publish this info.

"Hi everyone, we are a new delegate group providing hydra head services. Our pub keys for fee payment are as follows: [...]"
