### ISSUE TITLE
Build Haddock docs in CI

### ISSUE THREAD

**Issue by GeorgeFlerovsky** [mlabs-haskell/hydra-auction#85]

**Comment by uhbif19** [comment]
Do not think this is required.

We will have published Haddock when we release in Hackage/CHaP, right? By CI where can will we publish it? `mlabs-haskell` github pages seems to be non-existent.

Also I think it will take couple of tries to make Hercules work with Github Pages:

* https://docs.hercules-ci.com/hercules-ci-effects/guide/deploy-to-github-pages
* https://docs.hercules-ci.com/hercules-ci/effects/

So only thing needed is to check Haddock looks okay, I think. It does build locally in Nix, as I checked.

FYI @GeorgeFlerovsky

**Comment by GeorgeFlerovsky** [comment]
Yup, agreed. 👍
